config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # we are nesting the comments route in the topics route
  resources :topics do
    resources :comments
  end
  root 'topics#index'
end

# Prefix Verb   URI Pattern                Controller#Action
#     topics GET    /topics(.:format)          topics#index
#            POST   /topics(.:format)          topics#create
#  new_topic GET    /topics/new(.:format)      topics#new
# edit_topic GET    /topics/:id/edit(.:format) topics#edit
#      topic GET    /topics/:id(.:format)      topics#show
#            PATCH  /topics/:id(.:format)      topics#update
#            PUT    /topics/:id(.:format)      topics#update
#            DELETE /topics/:id(.:format)      topics#destroy
#       root GET    /                          topic#index

# Prefix Verb   URI Pattern                    Controller#Action
# new_user_session         GET    /users/sign_in(.:format)       devise/sessions#new
# user_session             POST   /users/sign_in(.:format)       devise/sessions#create
# destroy_user_session     DELETE /users/sign_out(.:format)      devise/sessions#destroy
# user_password            POST   /users/password(.:format)      devise/passwords#create
# new_user_password        GET    /users/password/new(.:format)  devise/passwords#new
# edit_user_password       GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
# user_registration        POST   /users(.:format)               devise/registrations#create
# new_user_registration    GET    /users/sign_up(.:format)       devise/registrations#new
# edit_user_registration   GET    /users/edit(.:format)          devise/registrations#edit
#                          PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy

      #     topic_comments GET    /topics/:topic_id/comments(.:format)          comments#index
      #                    POST   /topics/:topic_id/comments(.:format)          comments#create
      #  new_topic_comment GET    /topics/:topic_id/comments/new(.:format)      comments#new
      # edit_topic_comment GET    /topics/:topic_id/comments/:id/edit(.:format) comments#edit
      #      topic_comment GET    /topics/:topic_id/comments/:id(.:format)      comments#show
      #                    PATCH  /topics/:topic_id/comments/:id(.:format)      comments#update
      #                    PUT    /topics/:topic_id/comments/:id(.:format)      comments#update
      #                    DELETE /topics/:topic_id/comments/:id(.:format)      comments#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # ran rails generate model Comment content:text topic:references user:references
  # topic:references user:references created the belongs_to for us
  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :topics
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_topic, only: [:create, :edit, :update, :destroy]
  before_action :find_comment, only: [:edit, :update, :destroy]

  def create
    # to make a comment we need to first find the topic we want to comment on
    # we can find the topic by looking for the :topic_id which is in the comments schema
    # @topic = Topic.find(params[:topic_id])

    # we are building the comments from the topic and when we create something we need to make sure all the params are there
    @comment = @topic.comments.create(comment_params)

    # then we are assigning the comment's user_id to the current_user.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to topic_path(@topic)
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to topic_path(@topic)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to topic_path(@topic)
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_topic
    # to make a comment we need to first find the topic we want to comment on
    # we can find the topic by looking for the :topic_id which is in the comments schema
    @topic = Topic.find(params[:topic_id])
  end

  def find_comment
    @comment = @topic.comments.find(params[:id])
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all.order('created_at DESC')
  end

  def show
  end

  def new
    #@topic = Topic.new

    @topic = current_user.topics.build
  end

  def create
    # @topic = Topic.new(topic_params)

    @topic = current_user.topics.build(topic_params)

    if @topic.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to root_path
  end


  private
  def find_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content%></p>
  <p class="comment-posted-by">By: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

  <div class="links">
    <% if user_signed_in? %>
      <% if current_user.id == comment.user_id %>
        <%= link_to "Edit Comment ", edit_topic_comment_path(comment.topic, comment), class: "btn btn-primary" %>
        <!-- (comment.topic, comment) we are pinpointing the topic that owns that specific comment and then the comment itself -->
        <%= link_to "Delete Comment", topic_comment_path(comment.topic, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<!-- this form is for @topic and we are building out the comments for out topic,
comments dont exist without the topic -->
<%= simple_form_for ([ @topic, @topic.comments.build ]) do |t| %>
  <%= t.input :content, label: "Comments" %>
  <%= t.button :submit, class: "btn-custom"%>
<% end %>

app/views/comments/edit.html.erb
<% title "Placeholder Title" %>
<% description "Placeholder description." %>
<% keywords "Placeholder keywords" %>


<h1>Edit Comment</h1>
<%= simple_form_for ([ @topic, @comment]) do |t| %>
  <%= t.input :content, label: "Comments" %>
  <%= t.button :submit, class: "btn-custom"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav navbar navbar-inverse">
     <div class="container">
       <div class="navbar-header">
         <%= link_to "Fan Forum", root_path, class: "navbar-brand" %>
       </div>
         <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>
           <li><%= link_to 'Sign Out',  destroy_user_session_path, method: :delete %></li>
           <% else %>
           <li><%= link_to 'Log In',  new_user_session_path %></li>
           <li><%= link_to 'Sign Up',  new_user_registration_path %></li>
           <% end %>
         </ul>

         <% if user_signed_in? %>
         <p><%= link_to 'Post A Topic', new_topic_path, class: "navbar-text navbar-link" %></p>
         <% end %>

     </div>
   </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |t| %>
  <%= t.input :title, label: "Topic" %>
  <%= t.input :description %>
  <%= t.button :submit %>
<% end %>

app/views/topics/edit.html.erb
<% title "Placeholder Title" %>
<% description "Placeholder description." %>
<% keywords "Placeholder keywords" %>

<div class="col-md-8 col-md-offset-2">
  <h1 class="new-msg-header"> Post Topic </h1>
  <%= render "form" %>

</div>

app/views/topics/index.html.erb
<% title "Placeholder Title" %>
<% description "Placeholder description." %>
<% keywords "Placeholder keywords" %>


<% @topics.each do |topic| %>
  <div class="col-md-10 col-md-offset-1">
    <div class="message">
      <h2 class="message-title"><strong><%= topic.title %></strong></h2>
      <p><%= truncate(topic.description, length: 50) %></p>
      <p class="message-posted-by">Created <%= time_ago_in_words(topic.created_at) %> ago</p>
      <%= link_to "Join Convo", topic, class: "btn-custom" %>
    </div>
  </div>
<% end %>

app/views/topics/new.html.erb
<% title "Placeholder Title" %>
<% description "Placeholder description." %>
<% keywords "Placeholder keywords" %>

<div class="col-md-8 col-md-offset-2">
  <h1 class="new-msg-header"> Post Topic </h1>
  <%= render "form" %>

</div>

app/views/topics/show.html.erb
<% title "Placeholder Title" %>
<% description "Placeholder description." %>
<% keywords "Placeholder keywords" %>

<div class="col-md-10 col-md-offset-1">
  <div class="message-show">
    <h2><%= @topic.title %></h2>
    <p class="message-posted-by">Created <%= time_ago_in_words(@topic.created_at) %> ago</p>
    <p class="message-desc"><%= @topic.description %></p>

    <h3 class="comment-section-header">Comments:</h3>
    <p><%= render @topic.comments %></p>

    <h3 class="reply-to-msg">Join Discussion</h3>
    <!-- make sure we render the correct form by using comments/form -->
    <%= render "comments/form" %>
    <br>
    <div class="links btn-group">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
        <% if @topic.user_id == current_user.id %>
          <%= link_to "Edit", edit_topic_path, class: "btn btn-primary" %>
          <%= link_to "Delete", topic_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>